import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  page: { flex: 1, backgroundColor: '#f2f2f2' },
  scroll: { paddingTop: 12, paddingBottom: 64 },
  withBanner: { paddingTop: 0 },
  bannerWrap: { margin: 12, height: 180, borderRadius: 12, overflow: 'hidden' },
  banner: { height: 180, backgroundColor: '#e5e5e5' },
  dots: { position: 'absolute', bottom: 8, left: 0, right: 0, flexDirection: 'row', justifyContent: 'center', gap: 6 },
  dot: { height: 5, width: 5, borderRadius: 3, backgroundColor: 'rgba(255,255,255,.65)' },
  dotActive: { width: 15, backgroundColor: '#fff' },
  featureArea: { paddingHorizontal: 12 },
  featureCard: { flexDirection: 'row', borderRadius: 12, backgroundColor: '#fff', paddingVertical: 6 },
  feature: { flex: 1, alignItems: 'center' },
  featureIcon: { height: 56, width: 56, borderRadius: 28, backgroundColor: '#e5e5e5' },
  featureText: { color: '#666', fontSize: 12, lineHeight: 30 },
  recommend: { marginTop: 24, paddingHorizontal: 12 },
  sectionHead: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 12 },
  sectionTitle: { color: '#333', fontSize: 18, fontWeight: '500' },
  more: { color: '#14c8a5', fontSize: 13 },
  list: { gap: 12 },
  article: { minHeight: 66, flexDirection: 'row', alignItems: 'center', borderRadius: 8, padding: 12, backgroundColor: '#fff', shadowColor: '#000', shadowOpacity: .05, shadowRadius: 4, elevation: 1 },
  articleImage: { height: 66, width: 66, borderRadius: 8, backgroundColor: '#e5e5e5' },
  articleContent: { flex: 1, marginLeft: 12 },
  articleTitle: { color: '#333', fontSize: 16, fontWeight: '500' },
  articleDesc: { color: '#999', fontSize: 14, marginTop: 4, lineHeight: 19 },
  version: { alignItems: 'center', marginVertical: 12 },
  versionText: { color: '#999', fontSize: 12, lineHeight: 21 },
});
