#!/bin/bash
# 用法:  ./domain-shell new_domain_prefix

if [ $# -ne 1 ]; then
  echo "Usage: $0 <new_domain_prefix>"
  exit 1
fi

NEW_DOMAIN_PREFIX="$1"

sed -i "s/[a-zA-Z0-9][a-zA-Z0-9]*\.ngrok-free\.app/${NEW_DOMAIN_PREFIX}.ngrok-free.app/g" uni-vite/.env

sed -i "s/[a-zA-Z0-9][a-zA-Z0-9]*\.ngrok-free\.app/${NEW_DOMAIN_PREFIX}.ngrok-free.app/g" uni-spring-boot/src/main/java/com/lizhao/yizhao/authority/AuthorityCorsConfig.java

sed -i "s/[a-zA-Z0-9][a-zA-Z0-9]*\.ngrok-free\.app/${NEW_DOMAIN_PREFIX}.ngrok-free.app/g" uni-android/app/src/main/res/xml/network_security_config.xml

echo "新域名：${NEW_DOMAIN_PREFIX}.ngrok-free.app" 