CREATE TABLE `article` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `uuid` varchar(32) NOT NULL DEFAULT (REPLACE(LOWER(UUID()), '-', '')) COMMENT '唯一标识(无中划线，全小写)',
  `type` varchar(50) DEFAULT NULL COMMENT '类型',
  `sub_type` int DEFAULT NULL COMMENT '子类型',
  `title` varchar(255) NOT NULL COMMENT '标题',
  `author` varchar(100) DEFAULT NULL COMMENT '作者',
  `note` text COMMENT '备注/简介',
  `seq` int DEFAULT '99' COMMENT '排序序号',
  `class_name` varchar(100) DEFAULT NULL COMMENT 'CSS类名',
  `thumb` varchar(500) DEFAULT NULL COMMENT '缩略图URL',
  `url` varchar(500) DEFAULT NULL COMMENT '链接URL',
  `jump_to` enum('navigate','webview','web') DEFAULT NULL COMMENT '跳转方式',
  `content` json DEFAULT NULL COMMENT '内容数据(JSON格式)',
  `created_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_deleted` tinyint(1) DEFAULT '0' COMMENT '删除标识(0:正常 1:已删除)',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_uuid` (`uuid`),
  KEY `idx_type` (`type`),
  KEY `idx_seq` (`seq`),
  KEY `idx_created_time` (`created_time`),
  KEY `idx_is_deleted` (`is_deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='文章表';