CREATE TABLE `book` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `uuid` varchar(32) NOT NULL DEFAULT (REPLACE(LOWER(UUID()), '-', '')) COMMENT '唯一标识(无中划线，全小写)',
  `type` varchar(50) DEFAULT NULL COMMENT '类型',
  `title` varchar(255) NOT NULL COMMENT '书名',
  `author` varchar(100) DEFAULT NULL COMMENT '作者',
  `owner` varchar(100) DEFAULT NULL COMMENT '所有者',
  `score` decimal(3,1) DEFAULT NULL COMMENT '评分',
  `seq` int DEFAULT NULL COMMENT '排序序号',
  `cover` varchar(500) DEFAULT NULL COMMENT '封面图URL',
  `description` text COMMENT '描述',
  `summaries` json DEFAULT NULL COMMENT '摘要列表(JSON格式)',
  `tags` json DEFAULT NULL COMMENT '标签列表(JSON格式)',
  `highlights` json DEFAULT NULL COMMENT '精彩片段列表(JSON格式)',
  `created_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_deleted` tinyint(1) DEFAULT '0' COMMENT '删除标识(0:正常 1:已删除)',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_uuid` (`uuid`),
  KEY `idx_type` (`type`),
  KEY `idx_author` (`author`),
  KEY `idx_seq` (`seq`),
  KEY `idx_created_time` (`created_time`),
  KEY `idx_is_deleted` (`is_deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='书籍表';