CREATE TABLE `music` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `uuid` varchar(32) NOT NULL DEFAULT (REPLACE(LOWER(UUID()), '-', '')) COMMENT '唯一标识(无中划线，全小写)',
  `type` varchar(50) DEFAULT NULL COMMENT '类型',
  `title` varchar(255) NOT NULL COMMENT '歌曲标题',
  `singer` varchar(255) DEFAULT NULL COMMENT '歌手',
  `file_name` varchar(500) DEFAULT NULL COMMENT '文件名',
  `desc` text COMMENT '描述',
  `seq` int DEFAULT NULL COMMENT '排序序号',
  `url` varchar(500) NOT NULL COMMENT '音频文件URL',
  `cover` varchar(500) DEFAULT NULL COMMENT '封面图片URL',
  `lyric` varchar(500) DEFAULT NULL COMMENT '歌词文件URL',
  `created_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_deleted` tinyint(1) DEFAULT '0' COMMENT '删除标识(0:正常 1:已删除)',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_uuid` (`uuid`),
  UNIQUE KEY `uk_url` (`url`),
  KEY `idx_type` (`type`),
  KEY `idx_title` (`title`),
  KEY `idx_seq` (`seq`),
  KEY `idx_created_time` (`created_time`),
  KEY `idx_is_deleted` (`is_deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='音乐表';