CREATE TABLE `task` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `title` varchar(255) NOT NULL COMMENT '任务标题',
  `status` int DEFAULT 1 COMMENT '任务状态(1:未开始 2:进行中 3:已完成 4:已取消)',
  `publisher` varchar(100) DEFAULT NULL COMMENT '发布者',
  `targeter` varchar(100) DEFAULT NULL COMMENT '目标执行人',
  `content` text COMMENT '任务内容',
  `seq` int DEFAULT NULL COMMENT '排序序号',
  `progress` int DEFAULT '0' COMMENT '进度(0-100)',
  `finished` text COMMENT '完成标准',
  `awards` text DEFAULT NULL COMMENT '奖励(JSON格式)',
  `attachments` text DEFAULT NULL COMMENT '附件(JSON格式)',
  `works` text DEFAULT NULL COMMENT '作品/成果(JSON格式)',
  `publish_time` bigint DEFAULT NULL COMMENT '发布时间戳',
  `start_time` bigint DEFAULT NULL COMMENT '开始时间戳',
  `end_time` bigint DEFAULT NULL COMMENT '结束时间戳',
  `created_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_deleted` tinyint(1) DEFAULT '0' COMMENT '删除标识(0:正常 1:已删除)',
  PRIMARY KEY (`id`),
  KEY `idx_status` (`status`),
  KEY `idx_publisher` (`publisher`),
  KEY `idx_targeter` (`targeter`),
  KEY `idx_seq` (`seq`),
  KEY `idx_start_time` (`start_time`),
  KEY `idx_end_time` (`end_time`),
  KEY `idx_created_time` (`created_time`),
  KEY `idx_is_deleted` (`is_deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='任务表';