CREATE TABLE `video` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `uuid` varchar(32) NOT NULL DEFAULT (REPLACE(LOWER(UUID()), '-', '')) COMMENT '唯一标识(无中划线，全小写)',
  `type` varchar(50) DEFAULT NULL COMMENT '类型',
  `title` varchar(255) NOT NULL COMMENT '视频标题',
  `file_name` varchar(500) DEFAULT NULL COMMENT '文件名',
  `desc` varchar(500) DEFAULT NULL COMMENT '描述',
  `publisher` varchar(100) DEFAULT NULL COMMENT '发布者',
  `seq` int DEFAULT NULL COMMENT '排序序号',
  `url` varchar(500) NOT NULL COMMENT '视频文件URL',
  `cover` varchar(500) DEFAULT NULL COMMENT '封面图片URL',
  `object_fit` varchar(50) DEFAULT 'contain' COMMENT '显示模式(contain/cover等)',
  `ratio` decimal(4,2) DEFAULT '0.75' COMMENT '宽高比',
  `created_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_deleted` tinyint(1) DEFAULT '0' COMMENT '删除标识(0:正常 1:已删除)',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_uuid` (`uuid`),
  KEY `idx_type` (`type`),
  KEY `idx_title` (`title`),
  KEY `idx_seq` (`seq`),
  KEY `idx_created_time` (`created_time`),
  KEY `idx_is_deleted` (`is_deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='视频表';