export const CONTRAST_STATIC =[
  {
    "key": "an-ang",
    "title": "an（前鼻韵） 和 ang（后鼻韵）",
    "leftRhyme": "an",
    "rightRhyme": "ang",
    "left": [
      { "word": "早安", "mark": 1 },
      { "word": "答案", "mark": 1 },
      { "word": "蓝天", "mark": 1 },
      { "word": "万年", "mark": 1 },
      { "word": "看见", "mark": 1 },
      { "word": "元旦", "mark": 1 },
      { "word": "干净", "mark": 0 },
      { "word": "雨伞", "mark": 1 },
      { "word": "危险", "mark": 1 },
      { "word": "语言", "mark": 1 },
      { "word": "河边", "mark": 1 },
      { "word": "饭碗", "mark": 1 },
      { "word": "喜欢", "mark": 1 },
      { "word": "公园", "mark": 1 },
      { "word": "饭店", "mark": 1 },
      { "word": "光盘", "mark": 1 },
      { "word": "温暖", "mark": 1 },
      { "word": "探险", "mark": 0 },
      { "word": "栏杆", "mark": 0 },
      { "word": "安然", "mark": 1 },
      { "word": "竹竿", "mark": 1 },
      { "word": "沙滩", "mark": 1 },
      { "word": "帆船", "mark": 1 },
      { "word": "衬衫", "mark": 1 },
      { "word": "赶路", "mark": 0 },
      { "word": "站着", "mark": 0 }
    ],
    "right": [
      { "word": "太阳", "mark": 1 },
      { "word": "花香", "mark": 1 },
      { "word": "明亮", "mark": 1 },
      { "word": "灯光", "mark": 1 },
      { "word": "长江", "mark": 1 },
      { "word": "放学", "mark": 0 },
      { "word": "广场", "mark": 1 },
      { "word": "房子", "mark": 0 },
      { "word": "一样", "mark": 1 },
      { "word": "让步", "mark": 0 },
      { "word": "方向", "mark": 1 },
      { "word": "帮忙", "mark": 1 },
      { "word": "商场", "mark": 1 },
      { "word": "冰箱", "mark": 1 },
      { "word": "银行", "mark": 1 },
      { "word": "希望", "mark": 1 },
      { "word": "想象", "mark": 1 },
      { "word": "绵羊", "mark": 1 },
      { "word": "池塘", "mark": 1 },
      { "word": "窗户", "mark": 0 },
      { "word": "强壮", "mark": 1 },
      { "word": "风霜", "mark": 1 },
      { "word": "粮食", "mark": 1 },
      { "word": "海浪", "mark": 1 },
      { "word": "当然", "mark": 0 },
      { "word": "唱歌", "mark": 0 },
      { "word": "往来", "mark": 0 },
    ]
  },
  {
    "key": "en-eng",
    "title": "en（前鼻韵） 和 eng（后鼻韵）",
    "leftRhyme": "en",
    "rightRhyme": "eng",
    "left": [
      { "word": "什么", "mark": 0 },
      { "word": "文字", "mark": 0 },
      { "word": "认识", "mark": 0 },
      { "word": "早晨", "mark": 1 },
      { "word": "我们", "mark": 1 },
      { "word": "分数", "mark": 0 },
      { "word": "花盆", "mark": 1 },
      { "word": "身体", "mark": 0 },
      { "word": "认真", "mark": 1 },
      { "word": "本子", "mark": 0 },
      { "word": "门口", "mark": 0 },
      { "word": "森林", "mark": 0 },
      { "word": "温暖", "mark": 0 },
      { "word": "树根", "mark": 1 },
      { "word": "灰尘", "mark": 1 },
      { "word": "衬衫", "mark": 0 },
      { "word": "新闻", "mark": 1 },
    ],
    "right": [
      { "word": "生日", "mark": 0 },
      { "word": "灯光", "mark": 0 },
      { "word": "成长", "mark": 0 },
      { "word": "朋友", "mark": 0 },
      { "word": "声音", "mark": 0 },
      { "word": "风筝", "mark": 1 },
      { "word": "丰盛", "mark": 1 },
      { "word": "蜜蜂", "mark": 1 },
      { "word": "名称", "mark": 1 },
      { "word": "长城", "mark": 1 },
      { "word": "乘凉", "mark": 0 },
      { "word": "梦境", "mark": 0 }
    ]
  },
  {
    "key": "in-ing",
    "title": "in（前鼻韵） 和 ing（后鼻韵）",
    "leftRhyme": "in",
    "rightRhyme": "ing",
    "left": [
      { "word": "今天", "mark": 0 },
      { "word": "一斤", "mark": 1 },
      { "word": "森林", "mark": 1 },
      { "word": "进步", "mark": 0 },
      { "word": "毛巾", "mark": 1 },
      { "word": "拼音", "mark": 1 },
      { "word": "新年", "mark": 0 },
      { "word": "心里", "mark": 0 },
      { "word": "近处", "mark": 0 },
      { "word": "金鱼", "mark": 0 },
      { "word": "信心", "mark": 1 },
      { "word": "前进", "mark": 1 },
      { "word": "辛勤", "mark": 1 },
      { "word": "亲近", "mark": 0 },
      { "word": "阴天", "mark": 0 },
      { "word": "银杏", "mark": 0 },
    ],
    "right": [
      { "word": "听写", "mark": 0 },
      { "word": "明天", "mark": 0 },
      { "word": "晴天", "mark": 0 },
      { "word": "星星", "mark": 1 },
      { "word": "高兴", "mark": 1 },
      { "word": "事情", "mark": 1 },
      { "word": "安静", "mark": 1 },
      { "word": "蜻蜓", "mark": 1 },
      { "word": "电影", "mark": 1 },
      { "word": "透明", "mark": 1 },
      { "word": "姓名", "mark": 1 },
      { "word": "苹果", "mark": 0 },
      { "word": "青菜", "mark": 0 },
      { "word": "清水", "mark": 0 },
      { "word": "井口", "mark": 0 },
      { "word": "北京", "mark": 1 },
    ]
  }
]

export const SINGLE_STATIC = [
  {
    "key": "un",
    "title": "un（前鼻韵）",
    "rhyme": "un",
    "words": [
      { "word": "春天", "mark": 0 },
      { "word": "轮船", "mark": 0 },
      { "word": "昆仑", "mark": 1 },
      { "word": "论文", "mark": 0 },
      { "word": "群体", "mark": 0 },
      { "word": "困难", "mark": 0 },
      { "word": "裙子", "mark": 0 },
      { "word": "村庄", "mark": 0 },
      { "word": "温顺", "mark": 1 },
      { "word": "运气", "mark": 0 },
    ]
  },
  {
    "key": "ong",
    "title": "ong（后鼻韵）",
    "rhyme": "ong",
    "words": [
      { "word": "中国", "mark": 0 },
      { "word": "冬天", "mark": 0 },
      { "word": "松鼠", "mark": 0 },
      { "word": "雄鹰", "mark": 0 },
      { "word": "孔雀", "mark": 0 },
      { "word": "彩虹", "mark": 1 },
      { "word": "闹钟", "mark": 1 },
      { "word": "重要", "mark": 0 },
      { "word": "红色", "mark": 0 },
      { "word": "运动", "mark": 1 },
      { "word": "空气", "mark": 0 },

    ]
  }
]