import { Dimensions, StyleSheet } from 'react-native';
import { shadow } from '@/common/theme/shadow';

const { width: SCREEN_WIDTH } = Dimensions.get('window');
export const COVER_WIDTH = SCREEN_WIDTH - 48;
export const COVER_HEIGHT = 300;
export const FOOTER_HEIGHT = 156;
export const SETTINGS_BAR_HEIGHT = 44;

export const styles = StyleSheet.create({
  page: { flex: 1, backgroundColor: '#0f0f0f', overflow: 'hidden' },
  loading: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: '#0f0f0f' },
  loadingText: { color: '#fff' },
  background: { ...StyleSheet.absoluteFill, width: '100%', height: '100%', transform: [{ scale: 1.15 }] },
  mask: { ...StyleSheet.absoluteFill, backgroundColor: 'rgba(15,15,15,.72)' },
  body: { flex: 1, overflow: 'hidden' },
  back: { position: 'absolute', top: 4, left: 0, zIndex: 20, padding: 6 },
  main: { flex: 1, paddingTop: 48, paddingHorizontal: 24, gap: 40 },
  slidePage: { flex: 1, overflow: 'hidden' },
  slideBackground: { ...StyleSheet.absoluteFill, width: '100%', height: '100%', transform: [{ scale: 1.15 }] },
  slideMask: { ...StyleSheet.absoluteFill, backgroundColor: 'rgba(15,15,15,.72)' },
  slideBody: { flex: 1, paddingTop: 48, paddingHorizontal: 24, gap: 40 },
  swipeHint: { color: 'rgba(255,255,255,.7)', fontSize: 13, textAlign: 'center', marginTop: 24 },
  hero: { alignItems: 'center', gap: 24 },
  artwork: {
    width: COVER_WIDTH,
    height: COVER_HEIGHT,
    borderRadius: 12,
    backgroundColor: '#333',
    ...shadow({ opacity: .5, radius: 24, offset: { width: 0, height: 12 }, elevation: 8 }),
  },
  titles: { alignItems: 'center', gap: 8, width: '100%' },
  title: { color: '#fff', fontSize: 18, fontWeight: '600', maxWidth: '90%', textAlign: 'center' },
  artist: { color: 'rgba(255,255,255,.65)', fontSize: 14 },
  lyricBox: {
    flex: 1,
    width: '80%',
    alignSelf: 'center',
    minHeight: 120,
    maxHeight: 240,
    borderRadius: 16,
    overflow: 'hidden',
  },
  lyricScroll: { flex: 1 },
  lyricContent: { alignItems: 'center', paddingVertical: 8 },
  lyric: { color: 'rgba(255,255,255,.6)', fontSize: 13, lineHeight: 34, textAlign: 'center' },
  lyricActive: { color: '#fff', fontSize: 16, fontWeight: '700', transform: [{ scale: 1.05 }] },
  lyricEmpty: { flex: 1, color: 'rgba(255,255,255,.7)', fontSize: 13, textAlign: 'center', textAlignVertical: 'center' },
  overlay: {
    position: 'absolute',
    left: 0,
    right: 0,
    zIndex: 10,
    pointerEvents: 'box-none',
  },
  settingBar: {
    height: SETTINGS_BAR_HEIGHT,
    paddingLeft: 20,
    paddingRight: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  settings: { padding: 8, marginRight: -4, marginBottom: -4 },
  footer: {
    paddingTop: 16,
    paddingHorizontal: 20,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255,255,255,.1)',
    backgroundColor: 'rgba(15,15,15,.85)',
  },
  progress: { flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 16 },
  time: { width: 48, color: 'rgba(255,255,255,.6)', fontSize: 12, textAlign: 'center' },
  sliderTrack: { flex: 1, height: 20, justifyContent: 'center' },
  sliderRail: { height: 4, borderRadius: 2, backgroundColor: 'rgba(255,255,255,.2)', overflow: 'hidden' },
  sliderFill: { height: 4, borderRadius: 2, backgroundColor: '#fff' },
  sliderThumb: {
    position: 'absolute',
    top: 2,
    width: 16,
    height: 16,
    marginLeft: -8,
    borderRadius: 8,
    backgroundColor: '#fff',
  },
  controls: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  skip: {
    minWidth: 88,
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,.3)',
    alignItems: 'center',
  },
  skipDisabled: { opacity: 0.4 },
  controlText: { color: '#fff', fontSize: 13 },
  play: {
    width: 60,
    height: 60,
    borderRadius: 30,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ff6b5a',
    ...shadow({ color: '#ff6347', opacity: .4, radius: 12, offset: { width: 0, height: 6 }, elevation: 6 }),
  },
  modalMask: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(0,0,0,.45)' },
  sheet: { padding: 24, paddingBottom: 38, backgroundColor: 'rgba(15,15,15,.92)', borderTopLeftRadius: 18, borderTopRightRadius: 18 },
  sheetTitle: { color: '#fff', fontSize: 17 },
  pills: { flexDirection: 'row', marginTop: 18, borderRadius: 20, overflow: 'hidden', backgroundColor: '#555' },
  pill: { flex: 1, paddingVertical: 13, alignItems: 'center' },
  pillText: { color: '#fff' },
});
