import { StyleSheet } from 'react-native';
import { shadow } from '@/common/theme/shadow';

export const styles = StyleSheet.create({
  page: { flex: 1, backgroundColor: '#0f0f0f' },
  loading: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: '#0f0f0f' },
  loadingText: { color: '#fff' },
  background: { ...StyleSheet.absoluteFill, width: '100%', height: '100%', transform: [{ scale: 1.15 }] },
  mask: { ...StyleSheet.absoluteFill, backgroundColor: 'rgba(15,15,15,.72)' },
  content: { flex: 1 },
  header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 12 },
  back: { padding: 6 },
  backText: { color: '#fff', fontSize: 36, lineHeight: 36 },
  settings: { padding: 8 },
  settingsText: { color: '#fff', fontSize: 22 },
  hero: { alignItems: 'center', paddingTop: 12, paddingHorizontal: 24 },
  artwork: {
    width: 280,
    height: 280,
    borderRadius: 16,
    backgroundColor: '#333',
    ...shadow({ opacity: .5, radius: 24, offset: { width: 0, height: 12 }, elevation: 8 }),
  },
  title: { color: '#fff', fontSize: 20, fontWeight: '700', marginTop: 24, maxWidth: '90%', textAlign: 'center' },
  artist: { color: 'rgba(255,255,255,.65)', marginTop: 8, fontSize: 14 },
  lyricScroll: { flex: 1, marginTop: 16 },
  lyrics: { alignItems: 'center', paddingHorizontal: 32, paddingBottom: 12 },
  lyric: { color: 'rgba(255,255,255,.5)', fontSize: 15, lineHeight: 34, textAlign: 'center' },
  lyricActive: { color: '#fff', fontSize: 17, fontWeight: '700', transform: [{ scale: 1.05 }] },
  footer: {
    paddingTop: 16,
    paddingHorizontal: 20,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255,255,255,.1)',
    backgroundColor: 'rgba(15,15,15,.85)',
  },
  progress: { flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 16 },
  time: { color: 'rgba(255,255,255,.6)', width: 42, fontSize: 11, textAlign: 'center' },
  slider: { flex: 1, height: 16, justifyContent: 'center', backgroundColor: 'rgba(255,255,255,.2)', borderRadius: 4 },
  trackFill: { height: 4, borderRadius: 2, backgroundColor: '#fff' },
  controls: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  skip: {
    minWidth: 88,
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,.3)',
    alignItems: 'center',
  },
  controlText: { color: '#fff', fontSize: 13 },
  play: {
    width: 60,
    height: 60,
    borderRadius: 30,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ff6b5a',
    ...shadow({ color: '#ff6347', opacity: .4, radius: 12, offset: { width: 0, height: 6 }, elevation: 6 }),
  },
  playText: { color: '#fff', fontSize: 24 },
  modalMask: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(0,0,0,.45)' },
  sheet: { padding: 24, paddingBottom: 38, backgroundColor: 'rgba(15,15,15,.92)', borderTopLeftRadius: 18, borderTopRightRadius: 18 },
  sheetTitle: { color: '#fff', fontSize: 17 },
  pills: { flexDirection: 'row', marginTop: 18, borderRadius: 20, overflow: 'hidden', backgroundColor: '#555' },
  pill: { flex: 1, paddingVertical: 13, alignItems: 'center' },
  pillText: { color: '#fff' },
});
