import { StyleSheet } from 'react-native';
import { colors } from '@/common/theme/colors';
import { shadow } from '@/common/theme/shadow';

const mediaShadow = shadow({ opacity: .1, radius: 12, elevation: 2 });
const cardShadow = shadow({ opacity: .06, radius: 5, elevation: 1 });

export const styles = StyleSheet.create({
  modules: { width: '100%', alignSelf: 'stretch', paddingVertical: 16 },
  module: { width: '100%', alignSelf: 'stretch', marginBottom: 16, paddingHorizontal: 16 },
  moduleLast: { marginBottom: 0 },
  fullWidth: { paddingHorizontal: 0 },
  imageModule: { alignItems: 'stretch' },
  titleModule: { alignItems: 'center', backgroundColor: colors.white },
  mutedModule: { alignItems: 'center' },
  moduleItem: { marginBottom: 16 },
  moduleItemLast: { marginBottom: 0 },
  titleText: { fontSize: 18, fontWeight: '700', color: colors.textPrimary, textAlign: 'center', lineHeight: 28 },
  authorText: { fontSize: 14, color: colors.textMuted, textAlign: 'center', lineHeight: 22 },
  subTitleText: { fontSize: 14, color: colors.textMuted, textAlign: 'center', lineHeight: 22 },
  bodyText: { fontSize: 15, color: colors.textPrimary, lineHeight: 25 },
  richText: { fontSize: 15, color: colors.textPrimary, lineHeight: 25, textAlign: 'justify' },
  readModule: { alignItems: 'center' },
  readCard: {
    width: '100%',
    paddingHorizontal: 12,
    paddingTop: 28,
    paddingBottom: 22,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    backgroundColor: colors.white,
    ...cardShadow,
  },
  fullWidthReadCard: { borderRadius: 0 },
  readIcon: { position: 'absolute', top: 4, right: 9 },
  readInnerTitle: { fontSize: 16, fontWeight: '700', color: colors.textPrimary, textAlign: 'center', marginBottom: 3 },
  readInnerAuthor: { fontSize: 14, color: colors.textMuted, textAlign: 'center', marginBottom: 12 },
  readBodyText: { textAlign: 'center' },
  imageItem: { marginBottom: 16 },
  image: { width: '100%', alignSelf: 'stretch', borderRadius: 6, backgroundColor: '#f5f5f5' },
  fullWidthImage: { borderRadius: 0 },
  imageCaption: { marginTop: 6, marginBottom: 16, color: colors.textMuted, fontSize: 14, lineHeight: 21, textAlign: 'center' },
  videoModule: { marginBottom: 6 },
  mediaCard: { borderRadius: 6, overflow: 'hidden', backgroundColor: colors.white, ...mediaShadow },
  fullWidthMediaCard: { borderRadius: 0 },
  video: { width: '100%', backgroundColor: '#111' },
  fullWidthVideo: { borderRadius: 0 },
  videoCaption: { marginVertical: 12, color: colors.textMuted, fontSize: 14, lineHeight: 21, textAlign: 'center' },
  popupWrapper: { position: 'relative' },
  popupCover: { width: '100%', height: 230, backgroundColor: '#eee' },
  popupMask: { ...StyleSheet.absoluteFill, backgroundColor: 'rgba(0,0,0,.3)' },
  playIcon: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    width: 40,
    height: 40,
    marginTop: -20,
    marginLeft: -20,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,.5)',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0,0,0,.4)',
    opacity: .8,
  },
  playIconGlyph: { marginLeft: 3 },
  cardModule: { alignItems: 'center' },
  cardWrapper: {
    width: '100%',
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 6,
    backgroundColor: colors.white,
    ...cardShadow,
  },
  fullWidthCard: { borderRadius: 0 },
  cardImage: { width: '100%', backgroundColor: '#f5f5f5' },
  cardDesc: { padding: 32, color: colors.textPrimary, fontSize: 15, lineHeight: 25, textAlign: 'center' },
  previewPage: { flex: 1, backgroundColor: '#000', justifyContent: 'center' },
  previewClose: { position: 'absolute', right: 16, zIndex: 2, padding: 8 },
  previewScroll: { flex: 1 },
  previewSlide: { justifyContent: 'center', alignItems: 'center' },
  previewImage: { width: '100%', height: '100%' },
});
