import { StyleSheet } from 'react-native';
import { shadow } from '@/common/theme/shadow';

export const styles = StyleSheet.create({
  modules: { paddingVertical: 16 },
  module: { marginBottom: 16, paddingHorizontal: 16 },
  fullWidth: { paddingHorizontal: 0 },
  moduleText: { marginBottom: 16, color: '#333', fontSize: 15, lineHeight: 25 },
  moduleTitle: { alignItems: 'center' },
  centerMuted: { alignItems: 'center' },
  justify: { textAlign: 'justify' },
  readCard: {
    marginHorizontal: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: '#f0f0f0',
    borderRadius: 12,
    backgroundColor: '#fff',
    ...shadow({ opacity: .06, radius: 5, elevation: 1 }),
  },
  readIcon: { position: 'absolute', top: -8, right: 0, color: '#999', fontSize: 19 },
  image: { width: '100%', aspectRatio: 1.5, marginBottom: 8, borderRadius: 6, backgroundColor: '#f5f5f5' },
  caption: { marginTop: 8, color: '#999', fontSize: 14, lineHeight: 21, textAlign: 'center' },
  video: { width: '100%', height: 225, borderRadius: 6, overflow: 'hidden', backgroundColor: '#111' },
  fullWidthVideo: { borderRadius: 0 },
  popupWrapper: { position: 'relative', borderRadius: 6, overflow: 'hidden' },
  popupCover: { width: '100%', height: 230, backgroundColor: '#eee' },
  popupMask: { ...StyleSheet.absoluteFill, backgroundColor: 'rgba(0,0,0,.3)' },
  playIcon: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    width: 56,
    height: 56,
    marginTop: -28,
    marginLeft: -28,
    borderRadius: 28,
    borderWidth: 2,
    borderColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0,0,0,.25)',
  },
  playIconText: { color: '#fff', fontSize: 22, marginLeft: 4 },
  card: {
    marginHorizontal: 16,
    marginBottom: 16,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#f0f0f0',
    borderRadius: 6,
    backgroundColor: '#fff',
    ...shadow({ opacity: .06, radius: 5, elevation: 1 }),
  },
  cardImage: { width: '100%', height: 230, backgroundColor: '#f5f5f5' },
  cardText: { padding: 18, color: '#333', fontSize: 15, lineHeight: 25 },
  modalPage: { flex: 1, backgroundColor: '#000', justifyContent: 'center' },
  modalClose: { position: 'absolute', top: 48, right: 16, zIndex: 2, padding: 8 },
  modalCloseText: { color: '#fff', fontSize: 16 },
});
