server {
    listen 443 ssl;
    server_name app.izhao.com.cn;

    ssl_certificate     /opt/ssl/app.izhao.com.cn_nginx/app.izhao.com.cn_bundle.crt;
    ssl_certificate_key /opt/ssl/app.izhao.com.cn_nginx/app.izhao.com.cn.key;

    # 可选：增强 SSL 安全配置
    ssl_session_cache shared:SSL:1m;
    ssl_session_timeout 5m;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

    root /opt/www/yizhao;
    index index.html index.htm;

    location = / {
        return 302 /web/yizhao/;
    }

    location = /tech {
        return 301 /tech/;
    }

    location /tech/ {
        root /opt/www;
        index index.html;
        try_files $uri $uri/ /tech/index.html;
    }

    # 应用路径
    location /web/yizhao/ {
        alias /opt/www/yizhao/;
        index index.html index.htm;
        try_files $uri $uri/ /web/yizhao/index.html;
    }
}

server {
    listen 443 ssl;
    server_name www.izhao.com.cn;

    ssl_certificate     /opt/ssl/www.izhao.com.cn_nginx/www.izhao.com.cn_bundle.crt;
    ssl_certificate_key /opt/ssl/www.izhao.com.cn_nginx/www.izhao.com.cn.key;

    # 可选：增强 SSL 安全配置
    ssl_session_cache shared:SSL:1m;
    ssl_session_timeout 5m;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

    root /opt/www/yizhao;
    index index.html index.htm;

    location = / {
        return 302 /web/yizhao/;
    }

    location = /tech {
        return 301 /tech/;
    }

    location /tech/ {
        root /opt/www;
        index index.html;
        try_files $uri $uri/ /tech/index.html;
    }

    # 应用路径
    location /web/yizhao/ {
        alias /opt/www/yizhao/;
        index index.html index.htm;
        try_files $uri $uri/ /web/yizhao/index.html;
    }
}