export const PINYIN_TYPE_OPTIONS = [
	{ value: 'all', name: '全部（63）' },
	{ value: 'shengmu', name: '声母（23）' },
	{ value: 'yunmu', name: '韵母（24）' },
	{ value: 'whole', name: '整体认读（16）' },
]

export const PINYIN_CHARACTERS = [
	{ value: 'b', name: '播', type: 'shengmu' },
	{ value: 'p', name: '坡', type: 'shengmu' },
	{ value: 'm', name: '摸', type: 'shengmu' },
	{ value: 'f', name: '佛', type: 'shengmu' },
	{ value: 'd', name: '得', type: 'shengmu' },
	{ value: 't', name: '特', type: 'shengmu' },
	{ value: 'n', name: '讷', type: 'shengmu' },
	{ value: 'l', name: '勒', type: 'shengmu' },
	{ value: 'g', name: '哥', type: 'shengmu' },
	{ value: 'k', name: '科', type: 'shengmu' },
	{ value: 'h', name: '喝', type: 'shengmu' },
	{ value: 'j', name: '鸡', type: 'shengmu' },
	{ value: 'q', name: '旗', type: 'shengmu' },
	{ value: 'x', name: '兮', type: 'shengmu' },
	{ value: 'zh', name: '知', type: 'shengmu' },
	{ value: 'ch', name: '吃', type: 'shengmu' },
	{ value: 'sh', name: '狮', type: 'shengmu' },
	{ value: 'r', name: '日', type: 'shengmu' },
	{ value: 'z', name: '字', type: 'shengmu' },
	{ value: 'c', name: '此', type: 'shengmu' },
	{ value: 's', name: '思', type: 'shengmu' },
	{ value: 'y', name: '衣', type: 'shengmu' },
	{ value: 'w', name: '乌', type: 'shengmu' },
	
	{ value: 'a', name: '啊', type: 'yunmu' },
	{ value: 'o', name: '哦', type: 'yunmu' },
	{ value: 'e', name: '额', type: 'yunmu' },
	{ value: 'i', name: '医', type: 'yunmu' },
	{ value: 'u', name: '乌', type: 'yunmu' },
	{ value: 'ü', name: '鱼', type: 'yunmu', audio: 'v' },
	{ value: 'ai', name: '唉', type: 'yunmu' },
	{ value: 'ei', name: '诶', type: 'yunmu' },
	{ value: 'ui', name: '危', type: 'yunmu' },
	{ value: 'ao', name: '嗷', type: 'yunmu' },
	{ value: 'ou', name: '鸥', type: 'yunmu' },
	{ value: 'iu', name: '于', type: 'yunmu' },
	{ value: 'ie', name: '耶', type: 'yunmu' },
	{ value: 'üe', name: '曰', type: 'yunmu', audio: 've' },
	{ value: 'er', name: '耳', type: 'yunmu' },
	{ value: 'an', name: '安', type: 'yunmu' },
	{ value: 'en', name: '摁', type: 'yunmu' },
	{ value: 'in', name: '音', type: 'yunmu' },
	{ value: 'un', name: '温', type: 'yunmu' },
	{ value: 'ün', name: '云', type: 'yunmu', audio: 'vn' },
	{ value: 'ang', name: '昂', type: 'yunmu' },
	{ value: 'eng', name: '嗯', type: 'yunmu' },
	{ value: 'ing', name: '英', type: 'yunmu' },
	{ value: 'ong', name: '钟', type: 'yunmu' },
	
	{ value: 'zhi', name: '蜘', type: 'whole' },
	{ value: 'chi', name: '吃', type: 'whole' },
	{ value: 'shi', name: '狮', type: 'whole' },
	{ value: 'ri', name: '日', type: 'whole' },
	{ value: 'zi', name: '字', type: 'whole' },
	{ value: 'ci', name: '此', type: 'whole' },
	{ value: 'si', name: '思', type: 'whole' },
	{ value: 'yi', name: '衣', type: 'whole' },
	{ value: 'wu', name: '乌', type: 'whole' },
	{ value: 'yu', name: '鱼', type: 'whole' },
	{ value: 'ye', name: '椰', type: 'whole' },
	{ value: 'yue', name: '约', type: 'whole' },
	{ value: 'yuan', name: '渊', type: 'whole' },
	{ value: 'yin', name: '印', type: 'whole' },
	{ value: 'yun', name: '云', type: 'whole' },
	{ value: 'ying', name: '鹰', type: 'whole' },
]
