export const PHONETIC_TYPE_OPTIONS = [
	{ value: 'all', name: '全部（48）' },
	{ value: 'short', name: '短元音（7）' },
	{ value: 'long', name: '长元音（5）' },
	{ value: 'diphthong', name: '双元音（8）' },
	{ value: 'consonant', name: '辅音（28）' },
]

export const PHONETIC_SYMBOLS = [
	{ value: 'ɪ', name: 'sit', type: 'short', audio: 'i', alias: 'i', speak: 'ih' },
	{ value: 'e', name: 'bed', type: 'short', audio: 'e', alias: 'e', speak: 'eh' },
	{ value: 'æ', name: 'cat', type: 'short', audio: 'ae', alias: 'ae', speak: 'aeh' },
	{ value: 'ɒ', name: 'hot', type: 'short', audio: 'o', alias: 'o', speak: 'o' },
	{ value: 'ʌ', name: 'cup', type: 'short', audio: 'uh', alias: 'uh', speak: 'uh' },
	{ value: 'ʊ', name: 'book', type: 'short', audio: 'u', alias: 'u', speak: 'uuh' },
	{ value: 'ə', name: 'about', type: 'short', audio: 'schwa', alias: 'schwa', speak: 'uh' },

	{ value: 'iː', name: 'see', type: 'long', audio: 'ii', alias: 'i:', speak: 'ee' },
	{ value: 'ɑː', name: 'car', type: 'long', audio: 'aa', alias: 'a:', speak: 'ah' },
	{ value: 'ɔː', name: 'door', type: 'long', audio: 'oo', alias: 'o:', speak: 'aw' },
	{ value: 'uː', name: 'food', type: 'long', audio: 'uu', alias: 'u:', speak: 'oo' },
	{ value: 'ɜː', name: 'bird', type: 'long', audio: 'er', alias: 'er', speak: 'er' },

	{ value: 'eɪ', name: 'name', type: 'diphthong', audio: 'ei', alias: 'ei', speak: 'ay' },
	{ value: 'aɪ', name: 'time', type: 'diphthong', audio: 'ai', alias: 'ai', speak: 'eye' },
	{ value: 'ɔɪ', name: 'boy', type: 'diphthong', audio: 'oi', alias: 'oi', speak: 'oy' },
	{ value: 'əʊ', name: 'go', type: 'diphthong', audio: 'ou', alias: 'ou', speak: 'oh' },
	{ value: 'aʊ', name: 'now', type: 'diphthong', audio: 'au', alias: 'au', speak: 'ow' },
	{ value: 'ɪə', name: 'ear', type: 'diphthong', audio: 'ia', alias: 'ia', speak: 'eer' },
	{ value: 'eə', name: 'air', type: 'diphthong', audio: 'ea', alias: 'ea', speak: 'air' },
	{ value: 'ʊə', name: 'tour', type: 'diphthong', audio: 'ua', alias: 'ua', speak: 'oor' },

	{ value: 'p', name: 'pen', type: 'consonant', audio: 'p', alias: 'p', speak: 'puh' },
	{ value: 'b', name: 'bag', type: 'consonant', audio: 'b', alias: 'b', speak: 'buh' },
	{ value: 't', name: 'tea', type: 'consonant', audio: 't', alias: 't', speak: 'tuh' },
	{ value: 'd', name: 'dog', type: 'consonant', audio: 'd', alias: 'd', speak: 'duh' },
	{ value: 'k', name: 'cat', type: 'consonant', audio: 'k', alias: 'k', speak: 'kuh' },
	{ value: 'g', name: 'go', type: 'consonant', audio: 'g', alias: 'g', speak: 'guh' },
	{ value: 'f', name: 'fish', type: 'consonant', audio: 'f', alias: 'f', speak: 'fff' },
	{ value: 'v', name: 'very', type: 'consonant', audio: 'v', alias: 'v', speak: 'vvv' },
	{ value: 'θ', name: 'think', type: 'consonant', audio: 'th', alias: 'th', speak: 'th' },
	{ value: 'ð', name: 'this', type: 'consonant', audio: 'dh', alias: 'dh', speak: 'dh' },
	{ value: 's', name: 'sit', type: 'consonant', audio: 's', alias: 's', speak: 'sss' },
	{ value: 'z', name: 'zoo', type: 'consonant', audio: 'z', alias: 'z', speak: 'zzz' },
	{ value: 'ʃ', name: 'she', type: 'consonant', audio: 'sh', alias: 'sh', speak: 'shh' },
	{ value: 'ʒ', name: 'vision', type: 'consonant', audio: 'zh', alias: 'zh', speak: 'zh' },
	{ value: 'h', name: 'hat', type: 'consonant', audio: 'h', alias: 'h', speak: 'hhh' },
	{ value: 'tʃ', name: 'chair', type: 'consonant', audio: 'ch', alias: 'ch', speak: 'ch' },
	{ value: 'dʒ', name: 'job', type: 'consonant', audio: 'j', alias: 'j', speak: 'juh' },
	{ value: 'tr', name: 'tree', type: 'consonant', audio: 'tr', alias: 'tr', speak: 'tr' },
	{ value: 'dr', name: 'dress', type: 'consonant', audio: 'dr', alias: 'dr', speak: 'dr' },
	{ value: 'ts', name: 'cats', type: 'consonant', audio: 'ts', alias: 'ts', speak: 'ts' },
	{ value: 'dz', name: 'beds', type: 'consonant', audio: 'dz', alias: 'dz', speak: 'dz' },
	{ value: 'm', name: 'man', type: 'consonant', audio: 'm', alias: 'm', speak: 'mmm' },
	{ value: 'n', name: 'no', type: 'consonant', audio: 'n', alias: 'n', speak: 'nnn' },
	{ value: 'ŋ', name: 'sing', type: 'consonant', audio: 'ng', alias: 'ng', speak: 'ng' },
	{ value: 'l', name: 'like', type: 'consonant', audio: 'l', alias: 'l', speak: 'lll' },
	{ value: 'r', name: 'red', type: 'consonant', audio: 'r', alias: 'r', speak: 'rrr' },
	{ value: 'j', name: 'yes', type: 'consonant', audio: 'y', alias: 'y', speak: 'yuh' },
	{ value: 'w', name: 'we', type: 'consonant', audio: 'w', alias: 'w', speak: 'wuh' },
]
