export const LETTERS = [
	{ value: 'A', name: '/eɪ/' },
	{ value: 'B', name: '/biː/' },
	{ value: 'C', name: '/siː/' },
	{ value: 'D', name: '/diː/' },
	{ value: 'E', name: '/iː/' },
	{ value: 'F', name: '/ef/' },
	{ value: 'G', name: '/dʒiː/' },
	{ value: 'H', name: '/eɪtʃ/' },
	{ value: 'I', name: '/aɪ/' },
	{ value: 'J', name: '/dʒeɪ/' },
	{ value: 'K', name: '/keɪ/' },
	{ value: 'L', name: '/el/' },
	{ value: 'M', name: '/em/' },
	{ value: 'N', name: '/en/' },
	{ value: 'O', name: '/əʊ/' },
	{ value: 'P', name: '/piː/' },
	{ value: 'Q', name: '/kjuː/' },
	{ value: 'R', name: '/ɑː/' },
	{ value: 'S', name: '/es/' },
	{ value: 'T', name: '/tiː/' },
	{ value: 'U', name: '/juː/' },
	{ value: 'V', name: '/viː/' },
	{ value: 'W', name: '/dʌbljuː/' },
	{ value: 'X', name: '/eks/' },
	{ value: 'Y', name: '/waɪ/' },
	{ value: 'Z', name: '/ziː/' },
]
