export const LETTERS = [
	{ value: 'A', name: '/eɪ/', audio: '' },
	{ value: 'B', name: '/biː/', audio: '' },
	{ value: 'C', name: '/siː/', audio: '' },
	{ value: 'D', name: '/diː/', audio: '' },
	{ value: 'E', name: '/iː/', audio: '' },
	{ value: 'F', name: '/ef/', audio: '' },
	{ value: 'G', name: '/dʒiː/', audio: '' },
	{ value: 'H', name: '/eɪtʃ/', audio: '' },
	{ value: 'I', name: '/aɪ/', audio: '' },
	{ value: 'J', name: '/dʒeɪ/', audio: '' },
	{ value: 'K', name: '/keɪ/', audio: '' },
	{ value: 'L', name: '/el/', audio: '' },
	{ value: 'M', name: '/em/', audio: '' },
	{ value: 'N', name: '/en/', audio: '' },
	{ value: 'O', name: '/əʊ/', audio: '' },
	{ value: 'P', name: '/piː/', audio: '' },
	{ value: 'Q', name: '/kjuː/', audio: '' },
	{ value: 'R', name: '/ɑː/', audio: '' },
	{ value: 'S', name: '/es/', audio: '' },
	{ value: 'T', name: '/tiː/', audio: '' },
	{ value: 'U', name: '/juː/', audio: '' },
	{ value: 'V', name: '/viː/', audio: '' },
	{ value: 'W', name: '/dʌbljuː/', audio: '' },
	{ value: 'X', name: '/eks/', audio: '' },
	{ value: 'Y', name: '/waɪ/', audio: '' },
	{ value: 'Z', name: '/ziː/', audio: '' },
]
